# GLOBAL variables: which can be consumed by all charts
# images, contrail_env, contrail_env_vrouter_dpdk, contrail_env_vrouter_kernel
global:
  # section to configure images for all containers
  images:
    tags:
      kafka: "docker.io/opencontrailnightly/contrail-external-kafka:ocata-master-43"
      cassandra: "docker.io/opencontrailnightly/contrail-external-cassandra:ocata-master-43"
      redis: "redis:4.0.2"
      zookeeper: "docker.io/opencontrailnightly/contrail-external-zookeeper:ocata-master-43"
      contrail_control: "docker.io/opencontrailnightly/contrail-controller-control-control:ocata-master-43"
      control_dns: "docker.io/opencontrailnightly/contrail-controller-control-dns:ocata-master-43"
      control_named: "docker.io/opencontrailnightly/contrail-controller-control-named:ocata-master-43"
      config_api: "docker.io/opencontrailnightly/contrail-controller-config-api:ocata-master-43"
      config_devicemgr: "docker.io/opencontrailnightly/contrail-controller-config-devicemgr:ocata-master-43"
      config_schema_transformer: "docker.io/opencontrailnightly/contrail-controller-config-schema:ocata-master-43"
      config_svcmonitor: "docker.io/opencontrailnightly/contrail-controller-config-svcmonitor:ocata-master-43"
      webui_middleware: "docker.io/opencontrailnightly/contrail-controller-webui-job:ocata-master-43"
      webui: "docker.io/opencontrailnightly/contrail-controller-webui-web:ocata-master-43"
      analytics_api: "docker.io/opencontrailnightly/contrail-analytics-api:ocata-master-43"
      contrail_collector: "docker.io/opencontrailnightly/contrail-analytics-collector:ocata-master-43"
      analytics_alarm_gen: "docker.io/opencontrailnightly/contrail-analytics-alarm-gen:ocata-master-43"
      analytics_query_engine: "docker.io/opencontrailnightly/contrail-analytics-query-engine:ocata-master-43"
      analytics_snmp_collector: "docker.io/opencontrailnightly/contrail-analytics-snmp-collector:ocata-master-43"
      contrail_topology: "docker.io/opencontrailnightly/contrail-analytics-topology:ocata-master-43"
      build_driver_init: "docker.io/opencontrailnightly/contrail-vrouter-kernel-build-init:ocata-master-43"
      vrouter_agent: "docker.io/opencontrailnightly/contrail-vrouter-agent:ocata-master-43"
      vrouter_init_kernel: "docker.io/opencontrailnightly/contrail-vrouter-kernel-init:ocata-master-43"
      vrouter_dpdk: "docker.io/opencontrailnightly/contrail-vrouter-agent-dpdk:ocata-master-43"
      vrouter_init_dpdk: "docker.io/opencontrailnightly/contrail-vrouter-kernel-init-dpdk:ocata-master-43"
      dpdk_watchdog: "docker.io/opencontrailnightly/contrail-vrouter-net-watchdog:ocata-master-43"
      nodemgr: "docker.io/opencontrailnightly/contrail-nodemgr:ocata-master-43"
      dep_check: quay.io/stackanetes/kubernetes-entrypoint:v0.2.1
    imagePullPolicy: "IfNotPresent"


  # contrail_env section for all containers
  contrail_env:
    CONTROLLER_NODES: 6.6.6.6
    LOG_LEVEL: SYS_NOTICE
    CLOUD_ORCHESTRATOR: openstack
    AAA_MODE: cloud-admin
    CONTROL_DATA_NET_LIST: 6.6.6.0/24
    VROUTER_GATEWAY: 6.6.6.1

  # section of vrouter template for kernel mode
  contrail_env_vrouter_kernel:
    #AGENT_MODE: nic

  # section of vrouter template for dpdk mode
  contrail_env_vrouter_dpdk:
    #CPU_CORE_MASK: "0xf"
    #DPDK_UIO_DRIVER: uio_pci_generic
    #HUGE_PAGES: 32000
    #AGENT_MODE: dpdk
    #HUGE_PAGES_DIR: /dev/hugepages
    #DPDK_MEM_PER_SOCKET: 1024

  node:
    host_os: ubuntu

# Chart level variables like manifests, labels which are local to subchart
# Can be updated from the parent chart like below
# Example of overriding values of subchart, where contrail-vrouter is name of the subchart
contrail-vrouter:
  manifests:
    configmap_vrouter_dpdk: false
    daemonset_dpdk: false
