global:
  images:
    tags:
      nodemgr: "docker.io/opencontrailnightly/contrail-nodemgr:latest"
      contrail_status: "docker.io/opencontrailnightly/contrail-status:latest"
      node_init: "docker.io/opencontrailnightly/contrail-node-init:latest"
      analytics_api: "docker.io/opencontrailnightly/contrail-analytics-api:latest"
      contrail_collector: "docker.io/opencontrailnightly/contrail-analytics-collector:latest"
      analytics_alarm_gen: "docker.io/opencontrailnightly/contrail-analytics-alarm-gen:latest"
      analytics_query_engine: "docker.io/opencontrailnightly/contrail-analytics-query-engine:latest"
      analytics_snmp_collector: "docker.io/opencontrailnightly/contrail-analytics-snmp-collector:latest"
      contrail_topology: "docker.io/opencontrailnightly/contrail-analytics-topology:latest"
      dep_check: quay.io/stackanetes/kubernetes-entrypoint:v0.2.1
    imagePullPolicy: "IfNotPresent"
    # Specify imageCredentials
    imageCredentials:
      # registry: quay.io
      # username: username
      # password: password

  contrail_env:
    CONTROLLER_NODES: 10.87.65.248
    LOG_LEVEL: SYS_NOTICE
    CLOUD_ORCHESTRATOR: openstack
    AAA_MODE: cloud-admin

labels:
  analytics:
    node_selector_key: opencontrail.org/controller
    node_selector_value: "enabled"


dependencies:
  analytics:
    daemonset:
    - contrail-analyticsdb
    - contrail-config

# typically overriden by environmental
# values, but should include all endpoints
# required by this chart
endpoints:
  cluster_domain_suffix: cluster.local
  rabbitmq:
    auth:
      username: rabbitmq
      password: password
    path: /
    scheme: rabbit
    port:
      amqp:
        default: 5672
    hosts:
      default: rabbitmq
    host_fqdn_override:
       default: null
    domain_override: null
    namespace: openstack
  keystone:
    auth:
      username: admin
      password: password
      project_name: admin
      user_domain_name: default
      project_domain_name: default
      region_name: RegionOne
    hosts:
      default: keystone-api
    path:
      default: /v3
    port:
      admin:
        default: 35357
      api:
        default: 80
    scheme:
      default: http
    host_fqdn_override:
       default: null
    namespace: openstack

pod:
  lifecycle:
    upgrades:
      daemonsets:
        pod_replacement_strategy: RollingUpdate
        analytics:
          enabled: true
          min_ready_seconds: 0
          max_unavailable: 1

# Service related inputs are defined here
service:
  analytics_api_public_port: ""

# Ingress related inputs are defined here
ingress:
  analytics_api_host: "contrail-analytics-api"

manifests:
  configmap_analytics_env: true
  configmap_analytics_keystone: true
  configmap_analytics_rabbitmq: true
  daemonset_analytics: true
  service_analytics_api_server: true
  service_analytics_api_ingress: true
  ingress_analytics_api: true
