global:
  images:
    tags:
      nodemgr: "docker.io/opencontrailnightly/contrail-nodemgr:latest"
      contrail_status: "docker.io/opencontrailnightly/contrail-status:latest"
      node_init: "docker.io/opencontrailnightly/contrail-node-init:latest"
      contrail_control: "docker.io/opencontrailnightly/contrail-controller-control-control:latest"
      control_dns: "docker.io/opencontrailnightly/contrail-controller-control-dns:latest"
      control_named: "docker.io/opencontrailnightly/contrail-controller-control-named:latest"
      config_api: "docker.io/opencontrailnightly/contrail-controller-config-api:latest"
      config_devicemgr: "docker.io/opencontrailnightly/contrail-controller-config-devicemgr:latest"
      config_schema_transformer: "docker.io/opencontrailnightly/contrail-controller-config-schema:latest"
      config_svcmonitor: "docker.io/opencontrailnightly/contrail-controller-config-svcmonitor:latest"
      webui_middleware: "docker.io/opencontrailnightly/contrail-controller-webui-job:latest"
      webui: "docker.io/opencontrailnightly/contrail-controller-webui-web:latest"
      kube_manager: "docker.io/opencontrailnightly/contrail-kubernetes-kube-manager:latest"
      dep_check: quay.io/stackanetes/kubernetes-entrypoint:v0.2.1
    imagePullPolicy: "IfNotPresent"
    # Specify imageCredentials
    imageCredentials:
      # registry: quay.io
      # username: username
      # password: password

  contrail_env:
    CONTROLLER_NODES: 10.87.65.248
    LOG_LEVEL: SYS_NOTICE
    CLOUD_ORCHESTRATOR: openstack
    AAA_MODE: cloud-admin
    ANALYTICSDB_ENABLE: "true"
    ANALYTICS_ALARM_ENABLE: "true"
    ANALYTICS_SNMP_ENABLE: "true"

labels:
  control:
    node_selector_key: opencontrail.org/controller
    node_selector_value: "enabled"
  control_only:
    node_selector_key: opencontrail.org/controller
    node_selector_value: "enabled"
  config:
    node_selector_key: opencontrail.org/controller
    node_selector_value: "enabled"
  webui:
    node_selector_key: opencontrail.org/controller
    node_selector_value: "enabled"
  kube_manager:
    node_selector_key: opencontrail.org/controller
    node_selector_value: "enabled"

dependencies:
  config:
    daemonset:
    - contrail-configdb
  control:
    daemonset:
    - contrail-config
  webui:
    daemonset:
    - contrail-config
    - contrail-redis
  kube-manager:
    daemonset:
    - contrail-config

# Names of secrets used by bootstrap and environmental checks
secrets:
  keystone:
    admin: contrail-controller-keystone-admin

# typically overriden by environmental
# values, but should include all endpoints
# required by this chart
endpoints:
  cluster_domain_suffix: cluster.local
  rabbitmq:
    auth:
      username: guest
      password: guest
    path: /
    scheme: rabbit
    port:
      amqp:
        default: 5673
    hosts:
      default: rabbitmq
    host_fqdn_override:
       default: null
    domain_override: null
  keystone:
    auth:
      username: admin
      password: password
      project_name: admin
      user_domain_name: default
      project_domain_name: default
      region_name: RegionOne
    hosts:
      default: keystone
    path:
      default: /v3
    port:
      api:
        default: 80
    scheme:
      default: http
    host_fqdn_override:
       default: null
    namespace: openstack
  nova_metadata:
    name: nova
    hosts:
      default: metadata
    host_fqdn_override:
      default: null
    path:
      default: /
    scheme:
      default: 'http'
    port:
      metadata:
        public: 80
    namespace: openstack
  nova:
    name: nova
    hosts:
      default: nova-api
      public: nova
    host_fqdn_override:
      default: null
    path:
      default: "/v2/%(tenant_id)s"
    scheme:
      default: 'http'
    port:
      api:
        default: 8774
        public: 80
      novncproxy:
        default: 6080
    namespace: openstack
  network:
    name: neutron
    hosts:
      default: neutron-server
      public: neutron
    host_fqdn_override:
      default: null
    path:
      default: null
    scheme:
      default: 'http'
    port:
      api:
        default: 9696
        public: 80
    namespace: openstack
  image:
    name: glance
    hosts:
      default: glance-api
      public: glance
    host_fqdn_override:
      default: null
    path:
      default: null
    scheme:
      default: http
    port:
      api:
        default: 9292
        public: 80
    namespace: openstack
  volume:
    name: cinder
    hosts:
      default: cinder-api
      public: cinder
    host_fqdn_override:
      default: null
    path:
      default: '/v1/%(tenant_id)s'
    scheme:
      default:  'http'
    port:
      api:
        default: 8776
        public: 80
    namespace: openstack

pod:
  lifecycle:
    upgrades:
      daemonsets:
        pod_replacement_strategy: RollingUpdate
        control:
          enabled: true
          min_ready_seconds: 0
          max_unavailable: 1
        control_only:
          enabled: true
          min_ready_seconds: 0
          max_unavailable: 1
        config:
          enabled: true
          min_ready_seconds: 0
          max_unavailable: 1
        webui:
          enabled: true
          min_ready_seconds: 0
          max_unavailable: 1

# Service related inputs are defined here
service:
  config_api_public_port: ""

# Ingress related inputs are defined here
ingress:
  config_api_host: "contrail-config-api"
  webui_host: "contrail-webui"

# VolumeMounts related inputs are defined here
volumeMounts:
  host_usr_bin:
    hostPath: '/usr/bin'

manifests:
  configmap_controller_env: true
  configmap_controller_keystone: true
  configmap_controller_rabbitmq: true
  daemonset_config: true
  daemonset_control: true
  daemonset_control_only: false
  daemonset_webui: true
  daemonset_kube_manager: false
  service_config_api_server: true
  service_config_ingress: true
  service_web_controller: true
  service_webui_ingress: true
  ingress_webui: true
  ingress_config_api: true
  secret_controller_keystone_admin: true
