{{- if .Values.manifests.configmap_env }}
{{- $context := . }}
{{- $keystone_auth_host := tuple "keystone" "internal" $context | include "helm-toolkit.endpoints.hostname_short_endpoint_lookup" }}
{{- $rabbitmq_host := tuple "rabbitmq" "internal" $context | include "helm-toolkit.endpoints.hostname_short_endpoint_lookup" }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-analytics
data:
  {{- range $key, $value := .Values.contrail_env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-analytics-auth
data:
  KEYSTONE_AUTH_ADMIN_USER: {{ .Values.endpoints.keystone.auth.username }}
  KEYSTONE_AUTH_ADMIN_TENANT: {{ .Values.endpoints.keystone.auth.project_name }}
  KEYSTONE_AUTH_ADMIN_PASSWORD: {{ .Values.endpoints.keystone.auth.password }}
  KEYSTONE_AUTH_USER_DOMAIN_NAME: {{ .Values.endpoints.keystone.auth.user_domain_name }}
  KEYSTONE_AUTH_PROJECT_DOMAIN_NAME: {{ .Values.endpoints.keystone.auth.project_domain_name }}
  KEYSTONE_AUTH_URL_VERSION: {{ .Values.endpoints.keystone.path.default }}
  KEYSTONE_AUTH_HOST: {{ $keystone_auth_host }}
  KEYSTONE_AUTH_PROTO: {{ .Values.endpoints.keystone.scheme.default }}
  KEYSTONE_AUTH_ADMIN_PORT: {{ .Values.endpoints.keystone.port.admin.default | quote }}
  KEYSTONE_AUTH_PUBLIC_PORT: {{ .Values.endpoints.keystone.port.api.default | quote }}
  KEYSTONE_AUTH_REGION_NAME: {{ .Values.endpoints.keystone.auth.region_name | quote }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-analytics-rabbitmq
data:
  RABBITMQ_NODES: {{ $rabbitmq_host }}
  RABBITMQ_PORT: {{ .Values.endpoints.rabbitmq.port.amqp.default | quote }}
  RABBITMQ_USER: {{ .Values.endpoints.rabbitmq.auth.username | quote }}
  RABBITMQ_PASSWORD: {{ .Values.endpoints.rabbitmq.auth.password | quote }}
  RABBITMQ_USE_SSL: {{ .Values.contrail_env.RABBITMQ_USE_SSL | default "false" | quote }}
  RABBITMQ_VHOST: {{ .Values.endpoints.rabbitmq.path | default "/" | quote }}
{{- end }}
