images:
  tags:
    nodemgr: "docker.io/opencontrailnightly/contrail-nodemgr:ocata-master-17"
    build_driver_init: "docker.io/opencontrailnightly/contrail-agent-build-driver-init:ocata-master-17"
    vrouter_agent: "docker.io/opencontrailnightly/contrail-agent-vrouter:ocata-master-17"
    vrouter_init_kernel: "docker.io/opencontrailnightly/contrail-agent-vrouter-init-kernel:ocata-master-17"
    vrouter_dpdk: "docker.io/opencontrailnightly/contrail-agent-vrouter-dpdk:ocata-master-17"
    vrouter_init_dpdk: "docker.io/opencontrailnightly/contrail-agent-vrouter-init-kernel-dpdk:ocata-master-17"
    dpdk_watchdog: "docker.io/opencontrailnightly/contrail-agent-net-watchdog:ocata-master-17"
    dep_check: quay.io/stackanetes/kubernetes-entrypoint:v0.2.1
  imagePullPolicy: "IfNotPresent"

labels:
  vrouter_agent_kernel:
    node_selector_key: "opencontrail.org/vrouter-kernel"
    node_selector_value: "enabled"
  vrouter_agent_dpdk:
    node_selector_key: "opencontrail.org/vrouter-dpdk"
    node_selector_value: "enabled"

dependencies:
  vrouter_agent_kernel:
    daemonset:
    - contrail-config
    - contrail-control
  vrouter_agent_dpdk:
    daemonset:
    - contrail-config
    - contrail-control

contrail_env:
  vrouter_common:
    CONTROLLER_NODES: 10.87.65.248
    LOG_LEVEL: SYS_NOTICE
    CLOUD_ORCHESTRATOR: openstack
    AAA_MODE: cloud-admin
    #CONTROL_DATA_NET_LIST: 8.0.0.0/24
    #VROUTER_GATEWAY: 8.0.0.254
  vrouter_kernel:
    #AGENT_MODE: nic
  vrouter_dpdk:
    #CPU_CORE_MASK: "0xf"
    #DPDK_UIO_DRIVER: uio_pci_generic
    #HUGE_PAGES: 32000
    #AGENT_MODE: dpdk
    #HUGE_PAGES_DIR: /hugepages


node:
  host_os: ubuntu

# typically overriden by environmental
# values, but should include all endpoints
# required by this chart
endpoints:
  cluster_domain_suffix: cluster.local
  keystone:
    auth:
      username: admin
      password: password
      project_name: admin
      user_domain_name: default
      project_domain_name: default
      region_name: RegionOne
    hosts:
      default: keystone-api
    path:
      default: /v3
    port:
      admin:
        default: 35357
      api:
        default: 80
    scheme:
      default: http
    host_fqdn_override:
       default: null
    namespace: openstack

manifests:
  configmap_env: true
  daemonset_kernel: true
  daemonset_dpdk: false
