images:
  tags:
    nodemgr: "docker.io/opencontrail/contrail-nodemgr:5.0.0-175-centos7-newton"
    build_driver_init: "docker.io/opencontrail/contrail-agent-build-driver-init:5.0.0-189-ubuntu16-newton"
    vrouter_agent: "docker.io/opencontrail/contrail-agent-vrouter:5.0.0-175-centos7-newton"
    vrouter_init_kernel: "docker.io/opencontrail/contrail-agent-vrouter-init-kernel:5.0.0-175-ubuntu16-newton"
    vrouter_dpdk: "docker.io/opencontrail/contrail-agent-vrouter-dpdk:5.0.0-175-centos7-newton"
    vrouter_init_dpdk: "docker.io/opencontrail/contrail-agent-vrouter-init-kernel-dpdk:5.0.0-175-centos7-newton"
    dpdk_watchdog: "docker.io/opencontrail/contrail-agent-net-watchdog:5.0.0-175-centos7-newton"
    dep_check: quay.io/stackanetes/kubernetes-entrypoint:v0.2.1
  imagePullPolicy: "IfNotPresent"

labels:
  vrouter_agent_kernel:
    node_selector_key: openstack-compute-node
    node_selector_value: enabled
  vrouter_nodemgr:
    node_selector_key: openstack-compute-node
    node_selector_value: enabled
  vrouter_agent_dpdk:
    node_selector_key: "opencontrail.org/vrouter-dpdk"
    node_selector_value: "enabled"

dependencies:
  vrouter_agent_kernel:
    daemonset:
    - contrail-config
    - contrail-control
  vrouter_agent_dpdk:
    daemonset:
    - contrail-config
    - contrail-control

contrail_env:
  CONTROLLER_NODES: 10.87.65.248
  LOG_LEVEL: SYS_NOTICE
  CLOUD_ORCHESTRATOR: openstack
  AAA_MODE: cloud-admin
  #PHYSICAL_INTERFACE: p1p2
  #DPDK_COREMASK: 3-6
  #DPDK_UIO_DRIVER: uio_pci_generic
  #DPDK_HUGE_PAGES: 50
  #AGENT_MODE: dpdk

node:
  host_os: ubuntu

# typically overriden by environmental
# values, but should include all endpoints
# required by this chart
endpoints:
  cluster_domain_suffix: cluster.local
  keystone:
    auth:
      username: admin
      password: password
      project_name: admin
      user_domain_name: default
      project_domain_name: default
      region_name: RegionOne
    hosts:
      default: keystone-api
    path:
      default: /v3
    port:
      admin:
        default: 35357
      api:
        default: 80
    scheme:
      default: http
    host_fqdn_override:
       default: null

manifests:
  configmap_env: true
  daemonset_kernel: true
  daemonset_dpdk: false
