---
deploy_subnet: "192.168.1.0/24"
container_tag: >-
  {%- if zuul.change is defined -%}
    {{ zuul.change }}-{{ zuul.patchset }}
  {%- else -%}
    {{ contrail_container_tag }}
  {%- endif -%}
openstack_version: 'ocata'
