{{- if .Values.manifests.daemonset_config }}
{{- $_ := set .Values "images" .Values.global.images }}
{{- $context := . }}
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: contrail-config
spec:
  template:
    metadata:
      labels:
{{ tuple $context "opencontrail" "contrail-config" | include "helm-toolkit.snippets.kubernetes_metadata_labels" | indent 8 }}
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: {{ .Values.labels.config.node_selector_key }}
                operator: In
                values:
                - {{ .Values.labels.config.node_selector_value }}
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      initContainers:
{{ tuple $context .Values.dependencies.config nil | include "helm-toolkit.snippets.kubernetes_entrypoint_init_container" | indent 8 }}
      containers:
      - name: contrail-config-api
        image: {{ .Values.global.images.tags.config_api | quote }}
        imagePullPolicy: {{ default "" .Values.global.images.imagePullPolicy | quote }}
        ports:
        - name: api-port
          containerPort: {{ .Values.global.contrail_env.CONFIG_API_PORT | default 8082 }}
        - name: introspect-port
          containerPort: {{ .Values.global.contrail_env.CONFIG_API_INTROSPECT_PORT | default 8084 }}
        envFrom:
        - configMapRef:
            name: contrail-controller-env
        - configMapRef:
            name: contrail-controller-keystone
        - configMapRef:
            name: contrail-controller-rabbitmq
        volumeMounts:
        - mountPath: /var/log/contrail/
          name: contrail-log
        - mountPath: /etc/contrail/
          name: etc-contrail
        - mountPath: /var/crashes
          name: var-crashes-config
      - name: contrail-devicemgr
        image: {{ .Values.global.images.tags.config_devicemgr | quote }}
        imagePullPolicy: {{ default "" .Values.global.images.imagePullPolicy | quote }}
        envFrom:
        - configMapRef:
            name: contrail-controller-env
        - configMapRef:
            name: contrail-controller-keystone
        - configMapRef:
            name: contrail-controller-rabbitmq
        volumeMounts:
        - mountPath: /var/log/contrail/
          name: contrail-log
        - mountPath: /etc/contrail/
          name: etc-contrail
        - mountPath: /var/crashes
          name: var-crashes-config
      - name: contrail-schema-transformer
        image: {{ .Values.global.images.tags.config_schema_transformer | quote }}
        imagePullPolicy: {{ default "" .Values.global.images.imagePullPolicy | quote }}
        envFrom:
        - configMapRef:
            name: contrail-controller-env
        - configMapRef:
            name: contrail-controller-keystone
        - configMapRef:
            name: contrail-controller-rabbitmq
        volumeMounts:
        - mountPath: /var/log/contrail/
          name: contrail-log
        - mountPath: /etc/contrail/
          name: etc-contrail
        - mountPath: /var/crashes
          name: var-crashes-config
      - name: contrail-svcmonitor
        image: {{ .Values.global.images.tags.config_svcmonitor | quote }}
        imagePullPolicy: {{ default "" .Values.global.images.imagePullPolicy | quote }}
        envFrom:
        - configMapRef:
            name: contrail-controller-env
        - configMapRef:
            name: contrail-controller-keystone
        - configMapRef:
            name: contrail-controller-rabbitmq
        volumeMounts:
        - mountPath: /var/log/contrail/
          name: contrail-log
        - mountPath: /etc/contrail/
          name: etc-contrail
        - mountPath: /var/crashes
          name: var-crashes-config
      - name: contrail-config-nodemgr
        image: {{ .Values.global.images.tags.nodemgr | quote }}
        imagePullPolicy: {{ default "" .Values.global.images.imagePullPolicy | quote }}
        envFrom:
        - configMapRef:
            name: contrail-controller-env
        - configMapRef:
            name: contrail-controller-keystone
        env:
        - name: NODE_TYPE
          value: config
        - name: DOCKER_HOST
          value: "unix://mnt/docker.sock"
        volumeMounts:
        - mountPath: /mnt/docker.sock
          name: docker-unix-socket
        - mountPath: /var/log/contrail/
          name: contrail-log
        - mountPath: /etc/contrail/
          name: etc-contrail
        - mountPath: /var/crashes
          name: var-crashes-config
      volumes:
      - name: docker-unix-socket
        hostPath:
          path: /var/run/docker.sock
          type: Socket
      - name: etc-contrail
        hostPath:
          path: /etc/contrail
      - name: contrail-log
        hostPath:
          path: /var/log/contrail
      - name: var-crashes-config
        hostPath:
          path: /var/crashes/contrail/config
{{- end }}
